@startuml diagramme_de_sequence


actor Patient
participant SecretaireMedicale
participant RendezVous
participant Medecin
participant Facture

== Prise de rendez-vous ==
Patient -> SecretaireMedicale : demanderRendezVous(date, heure)
SecretaireMedicale -> RendezVous : creerRendezVous(date, heure, patient, medecin)
RendezVous -> SecretaireMedicale : confirmationRDV()
SecretaireMedicale -> Patient : confirmerRDV()

== Consultation ==
Patient -> Medecin : sePresenter(rdv)
Medecin -> Patient : effectuerConsultation()

== Génération de facture ==
Medecin -> Facture : creerFacture(montant, statut="en attente")
Facture -> Patient : envoyerFacture()
@enduml
